// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: profile/api/proto/profile.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PurchasePermissionRequest_PurchaseType int32

const (
	PurchasePermissionRequest_None     PurchasePermissionRequest_PurchaseType = 0
	PurchasePermissionRequest_ByCart   PurchasePermissionRequest_PurchaseType = 1
	PurchasePermissionRequest_ByWallet PurchasePermissionRequest_PurchaseType = 2
	PurchasePermissionRequest_ByCredit PurchasePermissionRequest_PurchaseType = 3
)

// Enum value maps for PurchasePermissionRequest_PurchaseType.
var (
	PurchasePermissionRequest_PurchaseType_name = map[int32]string{
		0: "None",
		1: "ByCart",
		2: "ByWallet",
		3: "ByCredit",
	}
	PurchasePermissionRequest_PurchaseType_value = map[string]int32{
		"None":     0,
		"ByCart":   1,
		"ByWallet": 2,
		"ByCredit": 3,
	}
)

func (x PurchasePermissionRequest_PurchaseType) Enum() *PurchasePermissionRequest_PurchaseType {
	p := new(PurchasePermissionRequest_PurchaseType)
	*p = x
	return p
}

func (x PurchasePermissionRequest_PurchaseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PurchasePermissionRequest_PurchaseType) Descriptor() protoreflect.EnumDescriptor {
	return file_profile_api_proto_profile_proto_enumTypes[0].Descriptor()
}

func (PurchasePermissionRequest_PurchaseType) Type() protoreflect.EnumType {
	return &file_profile_api_proto_profile_proto_enumTypes[0]
}

func (x PurchasePermissionRequest_PurchaseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PurchasePermissionRequest_PurchaseType.Descriptor instead.
func (PurchasePermissionRequest_PurchaseType) EnumDescriptor() ([]byte, []int) {
	return file_profile_api_proto_profile_proto_rawDescGZIP(), []int{0, 0}
}

type PurchasePermissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserCellPhone string                                 `protobuf:"bytes,1,opt,name=user_cell_phone,json=userCellPhone,proto3" json:"user_cell_phone,omitempty"`
	PurchaseType  PurchasePermissionRequest_PurchaseType `protobuf:"varint,2,opt,name=purchase_type,json=purchaseType,proto3,enum=proto.PurchasePermissionRequest_PurchaseType" json:"purchase_type,omitempty"`
}

func (x *PurchasePermissionRequest) Reset() {
	*x = PurchasePermissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_api_proto_profile_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PurchasePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchasePermissionRequest) ProtoMessage() {}

func (x *PurchasePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_api_proto_profile_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchasePermissionRequest.ProtoReflect.Descriptor instead.
func (*PurchasePermissionRequest) Descriptor() ([]byte, []int) {
	return file_profile_api_proto_profile_proto_rawDescGZIP(), []int{0}
}

func (x *PurchasePermissionRequest) GetUserCellPhone() string {
	if x != nil {
		return x.UserCellPhone
	}
	return ""
}

func (x *PurchasePermissionRequest) GetPurchaseType() PurchasePermissionRequest_PurchaseType {
	if x != nil {
		return x.PurchaseType
	}
	return PurchasePermissionRequest_None
}

type PurchasePermissionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Permission bool `protobuf:"varint,1,opt,name=permission,proto3" json:"permission,omitempty"`
}

func (x *PurchasePermissionResponse) Reset() {
	*x = PurchasePermissionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_api_proto_profile_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PurchasePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchasePermissionResponse) ProtoMessage() {}

func (x *PurchasePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_api_proto_profile_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchasePermissionResponse.ProtoReflect.Descriptor instead.
func (*PurchasePermissionResponse) Descriptor() ([]byte, []int) {
	return file_profile_api_proto_profile_proto_rawDescGZIP(), []int{1}
}

func (x *PurchasePermissionResponse) GetPermission() bool {
	if x != nil {
		return x.Permission
	}
	return false
}

var File_profile_api_proto_profile_proto protoreflect.FileDescriptor

var file_profile_api_proto_profile_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd9, 0x01, 0x0a, 0x19, 0x50, 0x75, 0x72,
	0x63, 0x68, 0x61, 0x73, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63,
	0x65, 0x6c, 0x6c, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x75, 0x73, 0x65, 0x72, 0x43, 0x65, 0x6c, 0x6c, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x52,
	0x0a, 0x0d, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75,
	0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x0c, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x40, 0x0a, 0x0c, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x42, 0x79, 0x43, 0x61, 0x72, 0x74, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x79, 0x57, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x42, 0x79, 0x43, 0x72, 0x65, 0x64,
	0x69, 0x74, 0x10, 0x03, 0x22, 0x3c, 0x0a, 0x1a, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x32, 0x64, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x59, 0x0a,
	0x12, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75, 0x72, 0x63,
	0x68, 0x61, 0x73, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x75,
	0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x70, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_profile_api_proto_profile_proto_rawDescOnce sync.Once
	file_profile_api_proto_profile_proto_rawDescData = file_profile_api_proto_profile_proto_rawDesc
)

func file_profile_api_proto_profile_proto_rawDescGZIP() []byte {
	file_profile_api_proto_profile_proto_rawDescOnce.Do(func() {
		file_profile_api_proto_profile_proto_rawDescData = protoimpl.X.CompressGZIP(file_profile_api_proto_profile_proto_rawDescData)
	})
	return file_profile_api_proto_profile_proto_rawDescData
}

var file_profile_api_proto_profile_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_profile_api_proto_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_profile_api_proto_profile_proto_goTypes = []interface{}{
	(PurchasePermissionRequest_PurchaseType)(0), // 0: proto.PurchasePermissionRequest.PurchaseType
	(*PurchasePermissionRequest)(nil),           // 1: proto.PurchasePermissionRequest
	(*PurchasePermissionResponse)(nil),          // 2: proto.PurchasePermissionResponse
}
var file_profile_api_proto_profile_proto_depIdxs = []int32{
	0, // 0: proto.PurchasePermissionRequest.purchase_type:type_name -> proto.PurchasePermissionRequest.PurchaseType
	1, // 1: proto.Profile.PurchasePermission:input_type -> proto.PurchasePermissionRequest
	2, // 2: proto.Profile.PurchasePermission:output_type -> proto.PurchasePermissionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_profile_api_proto_profile_proto_init() }
func file_profile_api_proto_profile_proto_init() {
	if File_profile_api_proto_profile_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_profile_api_proto_profile_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PurchasePermissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_api_proto_profile_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PurchasePermissionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_profile_api_proto_profile_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_api_proto_profile_proto_goTypes,
		DependencyIndexes: file_profile_api_proto_profile_proto_depIdxs,
		EnumInfos:         file_profile_api_proto_profile_proto_enumTypes,
		MessageInfos:      file_profile_api_proto_profile_proto_msgTypes,
	}.Build()
	File_profile_api_proto_profile_proto = out.File
	file_profile_api_proto_profile_proto_rawDesc = nil
	file_profile_api_proto_profile_proto_goTypes = nil
	file_profile_api_proto_profile_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProfileClient is the client API for Profile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfileClient interface {
	PurchasePermission(ctx context.Context, in *PurchasePermissionRequest, opts ...grpc.CallOption) (*PurchasePermissionResponse, error)
}

type profileClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileClient(cc grpc.ClientConnInterface) ProfileClient {
	return &profileClient{cc}
}

func (c *profileClient) PurchasePermission(ctx context.Context, in *PurchasePermissionRequest, opts ...grpc.CallOption) (*PurchasePermissionResponse, error) {
	out := new(PurchasePermissionResponse)
	err := c.cc.Invoke(ctx, "/proto.Profile/PurchasePermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServer is the server API for Profile service.
type ProfileServer interface {
	PurchasePermission(context.Context, *PurchasePermissionRequest) (*PurchasePermissionResponse, error)
}

// UnimplementedProfileServer can be embedded to have forward compatible implementations.
type UnimplementedProfileServer struct {
}

func (*UnimplementedProfileServer) PurchasePermission(context.Context, *PurchasePermissionRequest) (*PurchasePermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurchasePermission not implemented")
}

func RegisterProfileServer(s *grpc.Server, srv ProfileServer) {
	s.RegisterService(&_Profile_serviceDesc, srv)
}

func _Profile_PurchasePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchasePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServer).PurchasePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Profile/PurchasePermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServer).PurchasePermission(ctx, req.(*PurchasePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Profile_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Profile",
	HandlerType: (*ProfileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PurchasePermission",
			Handler:    _Profile_PurchasePermission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profile/api/proto/profile.proto",
}
